version: '3.8'

services:
  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:latest
    container_name: church_cms_supertokens
    restart: always
    environment:
      # Connects to the postgres container in the other stack via its container name 'church_cms_db'
      POSTGRESQL_CONNECTION_URI: "postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-password}@church_cms_db:5432/supertokens"
      API_KEYS: ${SUPERTOKENS_API_KEY}
    networks:
      - proxy
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  proxy:
    external: true
